load "Angle.rb"
load "Average.rb"
load "BlackHole.rb"
load "Circle.rb"
load "Coordinates.rb" 
# load "Equality.rb" is unnecesary because it is loaded in "SystemOfEquations.rb"
# but you should remove this comment if the "SystemOfEquations.rb" is missing or
# removed
load "Exponent.rb"
load "Fractions.rb"
load "Googol.rb"
load "Grade.rb"
load "Inequality.rb"
load "Rectangle.rb"
load "RectangularPrism.rb"
load "RightTriangle.rb"
load "Semicircle.rb"
load "Sphere.rb"
load "SystemOfEquations.rb"
load "SystemOFInequalities.rb"
load "Trapezoid.rb"
load "Triangle.rb"
load "TriangularPrism.rb"